#!/usr/bin/env python3
"""Write ~/.config/gtk-4.0/gtk.css from a theme palette. Usage: gtk.py <theme.js>

libadwaita 1.9 ignores @define-color and :root custom-property overrides coming
from the user stylesheet, so the surfaces are restyled by plain selectors, which
the user stylesheet does win. That covers the big areas only; anything not listed
here keeps stock Adwaita dark. Accent and light/dark come from gsettings instead
(see switch.sh) because libadwaita does honour those.
"""
import re, sys, os

src = open(sys.argv[1]).read()
c = dict(re.findall(r'(\w+):\s*"(#[0-9a-fA-F]{6})"', src))

css = f"""/* Generated by theme/gtk.py. Edits are overwritten on theme switch. */

window,
window.background {{
  background-color: {c['background']};
  color: {c['foreground']};
}}

headerbar,
.top-bar,
.toolbar,
windowhandle,
toolbarview > .top-bar {{
  background-color: {c['backgroundAlt']};
  color: {c['foreground']};
  box-shadow: inset 0 -1px {c['border']};
}}

.sidebar-pane,
.navigation-sidebar {{
  background-color: {c['backgroundAlt']};
  color: {c['foreground']};
}}

.content-pane,
.view,
listview,
gridview,
columnview {{
  background-color: {c['background']};
  color: {c['foreground']};
}}

popover > contents,
.card,
.osd {{
  background-color: {c['backgroundAlt']};
  color: {c['foreground']};
}}

entry,
searchbar entry {{
  background-color: {c['background']};
  color: {c['foreground']};
}}

separator {{
  background-color: {c['border']};
}}

.dim-label,
label.dim-label {{
  color: {c['foregroundAlt']};
}}
"""

path = os.path.expanduser("~/.config/gtk-4.0/gtk.css")
os.makedirs(os.path.dirname(path), exist_ok=True)
with open(path, "w") as f:
    f.write(css)
